### PR TITLE
WIP: Flatten the catalog

### PR DESCRIPTION
**Pull request by calebhailey**

### CODE REVIEW

**Comment by thoward** [comment]
I know the purpose of this is to flatten the structure, but it seems it might be a good idea to keep one layer of foldering, eg, put all these under a `~/templates/` folder... That will keep the home page from being very long before you get to the readme, but within the `tempates/` folder, it would be flat as you have it here. 

So the top level directory would just contain a `README.md`, `CONTRIBUTING.md`, and a `templates/` subfolder. If there are other things we need to add in the future (like config files or tests or somethign of that nature) then those would live at top level, and wouldn't get lost in the noise of a very long flatten structure.

**Comment by calebhailey** [comment]
@thoward I like that! Implemented this suggestion in https://github.com/sensu/catalog/pull/50/commits/f72838c9dba0d40989beed113bec5c92a4bc11aa and it's much better 👌

**Comment by thoward** [comment]
Is this still a WIP?

**Comment by calebhailey** [comment]
Closing in favor of #56

**Pull request closed without merging**
