### PR TITLE
initial commit for aws lambda metrics integratrion.

### PR DESCRIPTION
**Pull request by jspaleta**
Follows the pattern used in the aws-alb-monitoring integration but using the latest cloudwatch plugin asset version.

One difference of note.

This check does not use a cloudwatch plugin service preset for Lambda.. but instead sets the metrics to pull using an environment variable holding the json representation of the metrics config.

Please test on review especially the metric threshold logic.

### CODE REVIEW

**Comment by jspaleta** [comment]
Okay i have run a successul test using us-west-2 region in my local sensu-backend environment with the metric threshold section removed from the installable check definition produced by the check.
Do we just want to drop the metric thresholds for now and put them back in after we have a released version of sensu that support it?

**Comment by jspaleta** [comment]
I was able to test the metrics threshold.  I think I'm going to change the configured thresholds and just threshold on things that are obviously errors.  New commit inbound.

**Comment by calebhailey** [comment]
rebased against main

**Review by calebhailey — APPROVED** [review]
LGTM! Tested in our AWS account and it works great.

**Pull request merged**
